name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose -p toml-config

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Run tests
      run: cargo test --verbose --workspace